# Profile information
name: Angus Harrison Design 
title: Design - Angus Harrison
description: Industrial Design Portfolio
permalink: ':title/'

collections:
  INDN341:
  output: true
  INDN211:
  output: true
  INDN241:
  output: true


# Contact form
email: angusharrison1@gmail.com

# Comments
discus-identifier: # Add your Disqus identifier

# Paginate
paginate: 10
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
include: [_pages]
